#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
language: shell

jobs:
  include:
    - stage: Shellcheck
      name: Continuous integration
      before_script: shellcheck --version
      script: shellcheck .ci/*.sh

    - name: Source code
      before_script: shellcheck --version
      script: shellcheck src/*

    - stage: Checks
      name: Code style
      script: .ci/code-style.sh

    - name: Global installation
      script: .ci/global-install.sh > /dev/null || .ci/dump.sh global "$?"

    - name: Local installation
      script: .ci/local-install.sh > /dev/null || .ci/dump.sh local "$?"

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/usage.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Files
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/files.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/logging.sh > /dev/null || .ci/dump.sh local "$?"
