#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

language: shell

jobs:
  include:
    - stage: Checks
      name: Analysis
      before_script: shellcheck --version
      script: .ci/analysis.sh

    - stage: Installation
      name: Global
      os: linux
      script: .ci/global-install.sh > /dev/null || .ci/dump.sh global "$?"

    - stage: Installation
      name: Global
      os: osx
      script: .ci/global-install.sh > /dev/null || .ci/dump.sh global "$?"

    - stage: Installation
      name: Global
      os: windows
      script: .ci/global-install.sh > /dev/null || .ci/dump.sh global "$?"

    - name: Local
      script: .ci/local-install.sh > /dev/null || .ci/dump.sh local "$?"

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/usage.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Files
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/files.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/logging.sh > /dev/null || .ci/dump.sh local "$?"
