#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

language: shell

jobs:
  include:
    - stage: analysis
      before_script: shellcheck --version
      script: .ci/analysis.sh

    - stage: installation
      os: linux
      script: .ci/installation.sh
      after_failure: .ci/dump.sh

    - os: osx
      script: .ci/installation.sh
      after_failure: .ci/dump.sh

    - stage: tests
      os: linux
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/tests.sh
      after_failure: .ci/dump.sh

    - os: osx
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/tests.sh
      after_failure: .ci/dump.sh
