#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

language: shell

jobs:
  include:
    - stage: Analysis
      before_script: shellcheck --version
      script: .ci/analysis.sh

    - stage: Installation
      os: linux
      script: .ci/installation.sh > /dev/null || .ci/dump.sh "$?"

    - os: osx
      script: .ci/installation.sh > /dev/null || .ci/dump.sh "$?"

    - os: windows
      script: .ci/installation.sh > /dev/null || .ci/dump.sh "$?"

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/usage.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Files
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/files.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/logging.sh > /dev/null || .ci/dump.sh local "$?"
