#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Travis
      name: Scripts
      before_script: shellcheck --version
      script: shellcheck .travis/*.sh

    - stage: Checks
      name: Static analysis
      before_script: shellcheck --version
      script: shellcheck src/gitpack

    - name: Code style
      script: .travis/code-style.sh

    - name: Licensing
      services: docker
      install: docker pull fsfe/reuse:latest
      before_script: docker run fsfe/reuse reuse --version
      script: docker run -v "$TRAVIS_BUILD_DIR":/repo fsfe/reuse sh -c 'cd /repo && reuse lint'

    - stage: Execution
      name: Global installation
      install: sudo src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .travis/global-installation.sh

    - name: Local installation
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .travis/local-installation.sh

    - name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .travis/usage.sh
