#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Shellcheck
      name: Continuous integration
      before_script: shellcheck --version
      script: shellcheck .ci/*.sh

    - name: Source code
      before_script: shellcheck --version
      script: shellcheck src/*

    - stage: Checks
      name: Code style
      script: .ci/checks-code-style.sh

    - name: Global installation
      script: .ci/installation-global.sh > /dev/null || .ci/dump.sh global "$?"

    - name: Local installation
      script: .ci/installation-local.sh > /dev/null || .ci/dump.sh local "$?"

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/tests-usage.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Files
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/tests-files.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/tests-logging.sh > /dev/null || .ci/dump.sh local "$?"
