#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Initialization
      name: Scripts
      before_script: shellcheck --version
      script: shellcheck .travis/*.sh

    - stage: Checks
      name: Static analysis
      before_script: shellcheck --version
      script: shellcheck src/gitpack

    - name: Code style
      script: .travis/checks-code-style.sh

    - name: Licensing
      services: docker
      install: docker pull fsfe/reuse:latest
      before_script: docker run fsfe/reuse reuse --version
      script: docker run -v "$TRAVIS_BUILD_DIR":/repo fsfe/reuse sh -c 'cd /repo && reuse lint'

    - stage: Installation
      name: Global
      script: .travis/installation-global.sh

    - name: Local
      script: .travis/installation-local.sh

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .travis/tests-usage.sh

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .travis/tests-logging.sh
