#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

language: shell

jobs:
  include:
    - stage: analysis
      before_script: shellcheck --version
      script: .ci/analysis.sh

    - stage: test
      os: linux
      git:
        depth: false
      script: .ci/test.sh
      after_failure: .ci/dump.sh

    - os: osx
      git:
        depth: false
      script: .ci/test.sh
      after_failure: .ci/dump.sh
