#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: Checks
      name: Static analysis
      before_script: shellcheck --version
      script: shellcheck src/gitpack

    - name: Code style
      script: ( while read -r line; do test "$(echo "$line" | wc -m)" -le 81 || exit; done < src/gitpack )

    - name: Licensing
      services: docker
      install: docker pull fsfe/reuse:latest
      before_script: docker run fsfe/reuse reuse --version
      script: docker run -v "$TRAVIS_BUILD_DIR":/repo fsfe/reuse sh -c 'cd /repo && reuse lint'

    - stage: Execution
      name: Global installation
      install: sudo src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: sudo gitpack status github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT" | grep -q '^\[ok\]' &&
              gitpack status github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT" | grep -q '^\[nothing\]' &&
              sudo gitpack uninstall github.com/dominiksalvet/gitpack

    - name: Local installation
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: gitpack status github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT" | grep -q '^\[ok\]' &&
              gitpack uninstall github.com/dominiksalvet/gitpack

    - name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      before_script: gitpack about &&
                     gitpack help &&
                     gitpack clean
      script: gitpack status github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[nothing\]' &&
              gitpack install github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[install\]' &&
              gitpack install github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[installed\]' &&
              gitpack status github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[ok\]' &&
              gitpack list | grep -qF 'github.com/dominiksalvet/vhdldep' &&
              gitpack status github.com/dominiksalvet/vhdldep | grep -q '^\[older\]' &&
              gitpack install github.com/dominiksalvet/vhdldep | grep -q '^\[update\]' &&
              gitpack install github.com/dominiksalvet/vhdldep | grep -q '^\[installed\]' &&
              gitpack status github.com/dominiksalvet/vhdldep | grep -q '^\[ok\]' &&
              gitpack list | grep -qF 'github.com/dominiksalvet/vhdldep' &&
              gitpack status github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[newer\]' &&
              gitpack install github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[downgrade\]' &&
              gitpack install github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[installed\]' &&
              gitpack status github.com/dominiksalvet/vhdldep=2.1.0 | grep -q '^\[ok\]' &&
              gitpack list | grep -qF 'github.com/dominiksalvet/vhdldep' &&
              gitpack uninstall github.com/dominiksalvet/vhdldep | grep -q '^\[uninstall\]' &&
              gitpack uninstall github.com/dominiksalvet/vhdldep | grep -q '^\[uninstalled\]' &&
              gitpack status github.com/dominiksalvet/vhdldep | grep -q '^\[nothing\]' &&
              gitpack clean
