#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

os: linux
language: shell

jobs:
  include:
    - stage: Checks
      name: Static analysis
      before_script: shellcheck --version
      script: - shellcheck src/* &&
              - shellcheck .ci/*sh &&
              - false &&
              - .ci/code-style.sh

    - stage: installation
      name: Global
      script: .ci/global-install.sh > /dev/null || .ci/dump.sh global "$?"

    - name: Local
      script: .ci/local-install.sh > /dev/null || .ci/dump.sh local "$?"

    - stage: Tests
      name: Usage
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/usage.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Files
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/files.sh > /dev/null || .ci/dump.sh local "$?"

    - name: Logging
      install: src/gitpack install github.com/dominiksalvet/gitpack="$TRAVIS_COMMIT"
      script: .ci/logging.sh > /dev/null || .ci/dump.sh local "$?"
