#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: push

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: .ci/analysis.sh
  
  TestLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: .ci/test.sh
    - if: failure()
      run: .ci/dump.sh

  TestMacos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: .ci/test.sh
    - if: failure()
      run: .ci/dump.sh
