#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/*

    - name: Check install files
      run: |
        shellcheck .gitpack/data/.bash_completion
        shellcheck .gitpack/install/local/precp
