#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on:
  push:
    paths:
    - .github/**
    - .gitpack/**
    - src/*

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check CI scripts
      run: shellcheck .github/scripts/*

    - name: Check source files
      run: |
        shellcheck src/*
        .github/scripts/stylecheck src/*

    - name: Check GitPack files
      run: |
        shellcheck .gitpack/data/.bash_completion
        shellcheck .gitpack/install/local/precp

  Test:
    needs: Analysis
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: Run all tests
      run: .github/scripts/test

    - name: Dump GitPack information
      if: failure()
      run: .github/scripts/dump
