#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: push

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: .github/scripts/analysis.sh
  
  TestLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: .github/scripts/test.sh

  TestMacos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: .github/scripts/test.sh
