#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# github.com/dominiksalvet/gitpack
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check CI scripts
      run: shellcheck .github/scripts/*

    - name: Check source files
      run: shellcheck src/*

    - name: Check GitPack files
      run: |
        shellcheck .gitpack/data/.bash_completion
        shellcheck .gitpack/install/local/precp

  Test:
    needs: Analysis
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Run all tests
      run: .github/scripts/test

    - name: Dump GitPack information
      if: failure()
      run: .github/scripts/dump
